{{- if eq (toString .Values.deploymentMode) "Job" }}
{{- $fullName := include "kubedeploy.fullname" . -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kubedeploy.fullname" . }}
  labels:
    {{- include "kubedeploy.labels" . | nindent 4 }}
spec:
  backoffLimit: {{ .Values.jobspec.backoffLimit }}
  parallelism: {{ .Values.jobspec.parallelism }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kubedeploy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kubedeploy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: {{ .Values.jobspec.restartPolicy }}
      {{- if .Values.initContainer.enabled }}
      initContainers:
        - name: {{ include "kubedeploy.fullname" . }}-init
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.initContainer.repository }}:{{ .Values.initContainer.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.initContainer.pullPolicy }}
          command:
            {{- toYaml .Values.initContainer.command |nindent 12 }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if and (.Values.persistency.enabled) (lt (int .Values.replicaCount) 2) }}
          volumeMounts:
            - mountPath: {{ .Values.persistency.mountPath }}
              name: {{ $fullName }}-vol
          {{- end }}
          resources:
            {{- toYaml .Values.initContainer.resources | nindent 12 }}
      {{- end }}
      containers:
        - name: {{ include "kubedeploy.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command:
            {{- toYaml .Values.jobspec.command |nindent 12 }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
