{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: {{ include "kubedeploy.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "kubedeploy.fullname" . }}
  labels:
    {{- include "kubedeploy.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end  }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end  }}
  selector:
    matchLabels:
      {{- include "kubedeploy.selectorLabels" . | nindent 6 }}
{{- end }}
