---
include:
  - project: helm/charts
    file: '/ci-template/.gitlab-ci.yml'

deploychart:
  extends: .runner
  stage: deploy
  script:
    - kind export kubeconfig --name ${CI_COMMIT_SHORT_SHA}
    - helm upgrade --install ${RELEASE_NAME} ${CHART_NAME} --set image.repository=nginx --set image.tag=1.16.0 --wait --timeout 300s
