---
name: Cleanup
on:
  workflow_run:
    workflows: [Tests]
    types:
      - completed

jobs:
  cleanup:
    runs-on: docker-runner
    steps:
      - run: kind delete cluster --name ${GITHUB_SHA}
