---
name: Tests
on:
  push:
  workflow_dispatch:

env:
  CHART_NAME: kubedeploy
  RELEASE_NAME: testing

jobs:
  helmlint:
    runs-on: docker-runner
    steps:
      - uses: actions/checkout@v3
      - run: helm lint ${CHART_NAME}

  clusterinit:
    runs-on: docker-runner
    needs: helmlint
    steps:
      - run: kind create cluster --name ${GITHUB_SHA}

  deploychart:
    runs-on: docker-runner
    needs: clusterinit
    steps:
      - run: kind export kubeconfig --name ${GITHUB_SHA}
      - run: helm upgrade --install ${RELEASE_NAME} ${CHART_NAME} --set image.repository=nginx --set image.tag=1.16.0 --wait --timeout 300s

  verify:
    runs-on: docker-runner
    needs: deploychart
    steps:
      - run: kind export kubeconfig --name ${GITHUB_SHA}
      - run: kubectl wait --for=condition=available --timeout=300s deployment/${RELEASE_NAME}-${CHART_NAME}
      - run: kubectl get deployment ${RELEASE_NAME}-${CHART_NAME} -n default -o=jsonpath='{.status.replicas}' |grep 1
